apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: football_qa
    user: user
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1700
    isDefault: true
